app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin, current_user
from . import login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True, index=True)
    profile_pic_path = db.Column(db.String(255))
    password_secure = db.Column(db.String(255))

    @property
    def password(self):
        # block access to password
            raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_secure,password)

    def __repr__(self):
        return f'User {self.username}'



# class Timer:
#     def __init__ (self, title)

app/main/forms.py
from wtforms import TextAreaField,SubmitField,SelectField
from wtforms.validators import InputRequired
from flask_wtf import FlaskForm



class UpdateProfile(FlaskForm):
    bio = TextAreaField('Write something about yourself',validators = [InputRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy 
from config import config_options 
from flask_login import LoginManager
from flask_bootstrap import Bootstrap


db = SQLAlchemy()
bootstrap = Bootstrap()


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
    app = Flask(__name__)
   
    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # configure_uploads(app,photos)

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)


    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template,abort,redirect, url_for
from . import main 
from flask_login import login_required,current_user
from ..models import User
from .forms import UpdateProfile
from .. import db


@main.route ('/')
def index():

    message = "Hello World" 

    return render_template('index.html', message=message)

@main.route('/timer')
@login_required
def timer():
    return render_template('timer.html')

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = current_user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

app/templates/base.html
{% extends 'bootstrap/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block navbar%}
    {% include 'navbar.html' %}
    {% endblock %}
    {% block content %}

    {% endblock%}
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% block content%}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='css/style.css') }}">
<script src="{{url_for('static', filename='js/index.js')}}"></script>

<h1 style="color:#fff">POMODORO</h1>
{% endblock %}

app/templates/navbar.html
<div class="container" id="nav">
    <ul class="nav navbar-nav navbar-right">
     
     
      {% if current_user.is_authenticated %}
      <li><a href="/timer" style="color:white">TIMER</a></li>
      <li><a href="{{url_for('main.profile',uname=current_user.username)}}" id="profile" style="color:white" >Profile</a></li>
      &nbsp;&nbsp;
      <li><a href="{{url_for('auth.logout')}}" id="signout" style="color:white">Sign out</a></li>
      {% else %}
      <button class="btn-navbar"><a href="{{url_for('auth.login')}}" style="color:white">Sign in</a></button>
      {%endif%}
    </ul>
</div>
      

app/templates/profile/profile.html
{% extends 'base.html' %} 
{% block content %}

<div class="container">
    
    <div class="row">


        <div class="col-md-4">
            <h3> Name: {{user.username| capitalize}} </h3>

            {% if user.bio %}
            <p style="color:#fff"> Bio: {{user.bio}}</p>

            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %} 
            {% if user == current_user %}
            <button><a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a></button>
            
             {% endif %}

        </div>
        <div class="col-md-4">
            {% if user.profile_pic_path %}

            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail"> {%else%}
            <p>No profile picture</p>

            {% endif %} {% if user == current_user %}
            <form action="{{url_for('main.update_profile',uname=user.username)}}" method="post" enctype="multipart/form-data">

                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %} 
{% import 'bootstrap/wtf.html' as wtf %} {% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/timer.html
{% extends 'base.html' %}
{% block content%}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='css/style.css') }}">
<script src="{{url_for('static', filename='js/index.js')}}"></script>

<div id="pomodoro-app">
    <div id="container">
      <div id="timer">
        <div id="time">
          <span id="minutes">25</span>
          <span id="colon">:</span>
          <span id="seconds">00</span>
        </div>
        <div id="filler"></div>
      </div>
  
      <div id="buttons">
        <button id="work">Work</button>
        <button id="shortBreak">Short Break</button>
        <button id="longBreak">Long Break</button>
        <button id="stop">Stop</button>
      </div>
    </div>
  </div>
{% endblock %}